# Generated by Django 5.2.4 on 2025-07-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBCarsWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.TextField()),
                ('carbrand', models.TextField()),
                ('carmodel', models.TextField()),
                ('carprice', models.TextField()),
            ],
        ),
    ]
